name: C++ Builder

on: 
  push:
    branches:
    - main

jobs:

  build-mac:
   name: Mac Build
   runs-on: macos-latest
   steps:
    - name: Download Repository
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Install Vulkan SDK
      run: |
        curl -L "https://sdk.lunarg.com/sdk/download/1.2.162.0/mac/vulkansdk-macos-1.2.162.0.dmg?u=" -o vulkan-sdk.dmg
        hdiutil mount "./vulkan-sdk.dmg"
        cp -R "/volumes/vulkansdk-macos-1.2.162.0" "./"
        cd ./vulkansdk-macos-1.2.162.0
        ls -la
        sudo ./install_vulkan.py
        export VULKAN_SDK="$PWD/macOS/"
        export PATH=$VULKAN_SDK/bin:$PATH
        export DYLD_LIBRARY_PATH=$VULKAN_SDK/lib:$DYLD_LIBRARY_PATH
        export VK_ICD_FILENAMES=$VULKAN_SDK/etc/vulkan/icd.d/MoltenVK_icd.json
        export VK_LAYER_PATH=$VULKAN_SDK/etc/vulkan/explicit_layer.d
        echo "VULKAN_SDK" $VULKAN_SDK
        echo "DYLD_LIBRARY_PATH" $DYLD_LIBRARY_PATH
        vkvia
        vulkaninfo
    - name: Generate Solution
      run: |
        mkdir "build"
        cd build
        cmake .. -DVCPKG_TARGET_TRIPLET=x64-osx -DVCPKG_OVERLAY_PORTS="../extern/port-overlay"  -DCMAKE_TOOLCHAIN_FILE="../extern/vcpkg/scripts/buildsystems/vcpkg.cmake"
    - name: Debug
      if: ${{ failure() }}
      run: |
        cd ./build
        ls -la
        tail -n 1000 vcpkg-manifest-install.log
    - name: Build
      run: |
        cd ./build
        make
