name: C++ Builder

on: 
  push:
    branches:
    - main

jobs:

  build-mac:
   name: Mac Build
   runs-on: macos-latest
   steps:
    - name: Download Repository
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Install Vulkan SDK
      run: |
        curl -L "https://vulkan.lunarg.com/sdk/home#sdk/downloadConfirm/latest/mac/vulkan-sdk.dmg" -o vulkan-sdk.dmg
        ls -la
        hdiutil attach "./vulkan-sdk.dmg"
        ls -la
        cd /volumes
        ls -la
        cd ./vulkan-sdk
        ls -la
        sudo ./install_vulkan.py
    - name: Generate Solution
      run: |
        mkdir "build"
        cd build
        cmake .. -DVCPKG_TARGET_TRIPLET=x64-osx -DVCPKG_OVERLAY_PORTS="../extern/port-overlay"  -DCMAKE_TOOLCHAIN_FILE="../extern/vcpkg/scripts/buildsystems/vcpkg.cmake"
    - name: Debug
      if: ${{ failure() }}
      run: |
        cd ./build
        ls -la
        tail -n 1000 vcpkg-manifest-install.log
    - name: Build
      run: |
        cd ./build
        make
