name: C++ Builder

on: 
  push:
    branches:
    - main

jobs:

  build-mac:
   name: Mac Build
   runs-on: macos-latest
   steps:
    - name: Download Repository
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Install Vulkan SDK
      run: |
        curl -L "https://sdk.lunarg.com/sdk/download/1.2.162.0/mac/vulkansdk-macos-1.2.162.0.dmg?u=" -o vulkan-sdk.dmg
        hdiutil mount "./vulkan-sdk.dmg"
        cp -R "/volumes/vulkansdk-macos-1.2.162.0" "./"
        cd ./vulkansdk-macos-1.2.162.0
        sudo ./install_vulkan.py
    - name: Generate Solution
      run: |
        source ./vulkansdk-macos-1.2.162.0/setup-env.sh
        mkdir "build"
        cd build
        echo "VULKAN_SDK: $VULKAN_SDK"
        cmake .. -DVCPKG_TARGET_TRIPLET=x64-osx -DVCPKG_OVERLAY_PORTS="../extern/port-overlay"  -DCMAKE_TOOLCHAIN_FILE="../extern/vcpkg/scripts/buildsystems/vcpkg.cmake"
    - name: Debug
      if: ${{ failure() }}
      run: |
        cd ./extern/vcpkg/buildtrees/moltenvk/
        ls -la
        tail -n 1000 stdout-x64-osx.log
        cd x64-osx-dbg
        ls -la
    - name: Build
      run: |
        cd ./build
        make
